<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="tei2html" default="all">
    
    <!-- Eigenschaften -->
    <property name="tmpDir" value="./tmp"/>
    <property name="editions" value="./editions/complete-list"/>
    <property name="data" value="./editions/data"/>
    <property name="saxon.jar" value="${basedir}/saxon/saxon9he.jar"/>
    
    <!-- Gemeinsamer Classpath für Saxon -->
    <path id="saxon.classpath">
        <pathelement location="${saxon.jar}"/>
    </path>
    
    <!-- Targets -->
    <target name="clean">
        <delete dir="${tmpDir}"/>
        <delete dir="${data}"/>
    </target>
    
    <target name="prepare" depends="clean">
        <mkdir dir="${tmpDir}"/>
        <mkdir dir="${data}"/>
    </target>
    
    <!-- schnitzler-briefe_tage.xml, schnitzler-cmif_tage.xml, schnitzler-kultur und wienerschnitzler
         werden bereits im Workflow vor ant erzeugt (siehe .github/workflows/combine-import-lists.yml) -->
    
    <!-- Alle Events zusammenführen -->
    <target name="merge-events" depends="prepare">
        <xslt in="./editions/indices/tagesliste.xml" out="${tmpDir}/schnitzler-chronik.xml"
            style="./xslts/1_alle-events-zusammenkopieren.xsl">
            <factory name="net.sf.saxon.TransformerFactoryImpl"/>
            <classpath refid="saxon.classpath"/>
        </xslt>
        <move todir="${editions}">
            <fileset dir="${tmpDir}" includes="schnitzler-chronik.xml"/>
        </move>
    </target>
    
    <!-- Nach Datum gruppieren -->
    <target name="group-dates" depends="merge-events">
        <xslt in="${editions}/schnitzler-chronik.xml" out="${tmpDir}/schnitzler-chronik.xml"
            style="./xslts/2_nach-daten-gruppieren.xsl">
            <factory name="net.sf.saxon.TransformerFactoryImpl"/>
            <classpath refid="saxon.classpath"/>
        </xslt>
        <move todir="${editions}">
            <fileset dir="${tmpDir}" includes="schnitzler-chronik.xml"/>
        </move>
    </target>
    
    <!-- Einzeldateien erzeugen -->
    <target name="split-files" depends="group-dates">
        <!-- tmpDir neu anlegen, falls es vorher geleert wurde -->
        <mkdir dir="${tmpDir}"/>
        <xslt in="${editions}/schnitzler-chronik.xml" destdir="${tmpDir}"
            out="${data}/delete.xxx"
            style="./xslts/3_einzeldateien.xsl">
            <factory name="net.sf.saxon.TransformerFactoryImpl"/>
            <classpath refid="saxon.classpath"/>
        </xslt>
        <move todir="${data}">
            <fileset dir="${tmpDir}"/>
        </move>
    </target>
    
    <!-- Aufräumen -->
    <target name="cleanup" depends="split-files">
        <delete dir="${tmpDir}"/>
    </target>
    
    <!-- Gesamtziel -->
    <target name="all" depends="cleanup"/>
</project>
