name: Update schnitzler-tage from indivdual-lists/*_tage.xml

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Copy data to repo
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon, Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./dl_saxon.sh
    - name: run xsl
      run: |
        ./ant
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated schnitzler-tage.xml
